### ISSUE TITLE
Delay between workers?

### ISSUE THREAD

**Issue by BlackConure** [gammazero/workerpool#1]
I was looking at your implementation for a worker pool in Go and I really like the way you approached it; in that you can submit at any time and it adds it to the queue.  Most implementations seem to operate off of a set of known tasks a priori.  

Secondly, it doesn't delay the submission channel and this is very important because in my case if I lag even just a few milliseconds (or 10s of milliseconds) from the event firing, I will miss the next event.  So far so good.

However, what I am struggling to figure out is how to put a delay in somewhere so that I can set the time between executions for each task without interfering with the incoming events.   This delay is especially needed for the first set of workers that get added to the pool because they get fired off simultaneously.   I need at least *some* spacing for the web server to breathe a bit before I lay siege on it.  ;)   

Any suggestions on where I can add this delay?

**Comment by ajgillis** [comment]
It would be difficult to throttle task execution by using a delay, since you cannot know when the goroutines are scheduled relative to each other.  Also, this seems to mean that you want to execute all the tasks serially, so that there is some wait time between each.  Instead of delaying tasks, could you size the worker pool so that the number of concurrent workers is within the webserver's capacity? 

If you do push the webserver beyond its capacity, then the worker pool should just build up queued tasks that well get executed when the web server is able to handle them.  In other words, let the back pressure of a blocking web server limit task execution speed instead of trying to determine the correct delay.  I would think it difficult to come up with the most correct speed to feed the webserver.  One purpose of the worker pool is exactly this - to queue tasks, without blocking the producer, until the task consumer is able to consume them.   

If you feel a task execution delay is your only choice (which I would encourage careful examination), then you could give each task a timer (`time.After()`) that fires at the time the task should execute.  The task can just wait on the timer, and then finish execution after the timer fires. You probably want to take an approach that reuses timers so as not to generate excess garbage (used timers) that causes GC work.

**Comment by gammazero** [comment]
It would be difficult to throttle task execution by using a delay, since you cannot know when the goroutines are scheduled relative to each other. Also, this seems to mean that you want to execute all the tasks serially, so that there is some wait time between each. Instead of delaying tasks, could you size the worker pool so that the number of concurrent workers is within the webserver's capacity?

If you do push the webserver beyond its capacity, then the worker pool should just build up queued tasks that well get executed when the web server is able to handle them. In other words, let the back pressure of a blocking web server limit task execution speed instead of trying to determine the correct delay. I would think it difficult to come up with the most correct speed to feed the webserver. One purpose of the worker pool is exactly this - to queue tasks, without blocking the producer, until the task consumer is able to consume them.

If you feel a task execution delay is your only choice (which I would encourage careful examination), then you could give each task a timer (time.After()) that fires at the time the task should execute. The task can just wait on the timer, and then finish execution after the timer fires. You probably want to take an approach that reuses timers so as not to generate excess garbage (used timers) that causes GC work.

**Comment by BlackConure** [comment]
The problem is not the capacity of the web server.   In fact, it is sitting on a 128 core machine with 2TB of RAM so it can handle just about anything I can throw at it.   

The requests that I am making are actually requests to execute a process that exports data to another system.   I don't necessarily care what order it handles the requests, but I do care that there is a minimum amount of breathing time between each one.   

What we found is that when it starts the process to perform the export, the back end database it is connecting to needs a bit more time to handle the login requests.  With a flood, it gets into a race and deadlock condition for resources, but only during the login (which takes 1-2 seconds).   

As for using time.After(), I tried that (of sorts) but the issue is that (as you implied) it is not synchronized across running workers, and because each worker doesn't have a specific time of execution, I can't just operate off of the worker being done.   What I need is a cadence timer....just not sure where to do that.

Thoughts?

**Comment by gammazero** [comment]
If it is a matter of signaling one or more tasks that run only after the necessary login is completed, then create a channel that all the non-login tasks wait on.  When the login task completes, then it can close the channel to broadcast its completion to all waiting threads.  Just make sure the login task is run first and is not queued.  Another variation of this may be for the tasks to re-enqueue themselves if some execution criteria has not yet been met (e.g. login complete)

Maybe the database tasks, or database portion of the tasks, can be put on a separate queue so that you can set proper cadence for their execution.  That separate queue could be a channel with a cadence-setting goroutine reading from the channel (or separate worker pool with size of 1).  

To implement any kind of a cadence regulator between separate goroutines, you need some form of synchronization between them -- pull tasks periodically from single channel, use channels to signal ready/done, use `sync` objects, etc.  

An execution delay, without synchronization is not sufficient.  Even if there was an execution delay added into the worker pool task reception loop, there would be no way to tell how long it had been since the last task ran (since you do not have control of when separate go routines are scheduled).  You could wait 5 seconds before each task, but after that 5 second wait it would still be possible that a goroutine for a previous task was run only a millisecond ago.

**Comment by gammazero** [comment]
My feeling is that the solution to this issue is within the application's domain, not in the problem domain addressed by workerpool.  Therefore, unless there is some hook that workerpool needs provide to enable certain solutions, then I suggest this issue be closed.

**Comment by BlackConure** [comment]
Actually, I have been meaning to post this, but have been pretty busy.   I did end up putting in a cadence timer for workers (and it works like a champ!) but I needed to clean up the timeout; it is created every time and I have to push it up out of the loop...just hadn't gotten time to get that done.  

Let me know your thoughts.   I can clean it up later and re-submit, but the general idea is this:

I augmented the structure of the WorkerPool
```
type WorkerPool struct {
	maxWorkers   		int
	timeout      		time.Duration
	taskQueue    		chan func()
	readyWorkers 		chan chan func()
	stoppedChan  		chan struct{}
	workerDelay  		time.Duration
	ticker       		*time.Ticker
	mutex		 		*sync.Mutex
}

```
Then added a function to set the delay

```
func (p *WorkerPool) SetWorkerDelay( delay time.Duration ) {
	p.ticker = time.NewTicker(delay)
	p.workerDelay = delay
}

```
In your main loop, I added two lines:

```
select {
case workerTaskChan = <-p.readyWorkers:
	// ADDED: Space out the workers until the cadence timer ticks
	p.delayWorker()

	// A worker is ready, so give task to worker.
	workerTaskChan <- task

default:
	// No workers ready.
	// Create a new worker, if not at max.
	if workerCount < p.maxWorkers {
		workerCount++

		go func(t func()) {
			// ADDED: Space out the workers until the cadence timer ticks
			p.delayWorker()

			startWorker(startReady, p.readyWorkers)
```

Then added the delay function (again, needs to put the timeout out of this loop).
```
func (p *WorkerPool) delayWorker() {
	p.mutex.Lock()

	if( p.ticker != nil ) {

		// Clear out any cadence tickers that have fired
		for len(p.ticker.C) > 0  {
			<- p.ticker.C
		}

		// Set a timeout in case the last worker is running
		timeout := time.After(time.Millisecond * time.Duration(p.workerDelay))
	
		loop:
		for{ 
			select {
			case <- p.ticker.C:
				break loop
			case <- timeout:
				break loop
			}
		}

	}

	p.mutex.Unlock()
}

```

**Comment by gammazero** [comment]
Adding a delay to the dispatch loop, and changing the base worker pool implementation, incurs mutex lock/unlock overhead and serializes tasks through the `delayWorker()`.  This still seems specific to your problem domain, and there are a few issues with the implementation.  Instead of addressing that,  I would like to propose a different approach:

Have a function that each concurrent task goroutine can call, that will return in one goroutine at a time and at a rate no grater then one per delay period: 

https://play.golang.org/p/vWcC6A52cR

You can also use that to create different types of task (paced task and normal task), both of which can be submitted to the same `WorkerPool`.

**Comment by BlackConure** [comment]
Thanks for the suggestion.   I think I see what you are eluding to, but I will need to try it out to be sure.   That said, though, I still see a lot of reasons why something like this would be a welcome part of a worker pool implementation itself, rather than relying on the caller to implement a secondary cadence gate.

Think about a real-time web traffic monitor.   You really don't care about when it writes the entry to the database, just that it does write it.   What you do care about, however, is that you don't lose any packets because you are busy waiting on the database to catch up.    And, not to overload the database, you give it a bit of a breather to execute the stored procedures over time (and avoid deadlocks and other such corner cases).

My case is similar in nature to this.   Serial or parallel execution is not important; just that nothing is lost and the recipient of the worker has time to breathe.   Ultimately up to you if you think it worthy, but I thought at least it would be a good idea to feed back to you.

**Comment by gammazero** [comment]
Let me know what you think of https://github.com/gammazero/workerpool/pull/2
This adds a cadence regulator (pacer) that has a `Pace` function that wraps a task function to turn it into a paced task function that can be submitted to the workerpool.

Note: The tasks are paced such that their start time is delayed by the delay time from the **start** of the previous paced task, not from it's end time.  Also, tasks wrapped by separate pacers will not interfere with each other and are paced independently.

**Comment by BlackConure** [comment]
You da man!     This was indeed a much better way to do it than I had attempted.     Just the concept of having multiple pacers without it being global to the queue alone is awesome!   

I took a little liberty and added the ability to pause and resume the pacer as well; giving you full control of the pacers.

Once again, thanks!  👍 

```
// Returns status of paused state
func (p *Pacer) IsPaused() bool {
	return p.paused
}

// Pause holds off execution of any tasks by the pacer
func (p *Pacer) Pause() {
	p.paused = true
	return
}

// Resume continues execution after a pause.  
func (p *Pacer) Resume() {
	p.paused = false
	return
}
```
